# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: jiashun-wang/blog-SanYeCao
  branch: master
  base_url: https://sveltia-cms-auth.1043210554.workers.dev # URL of your OAuth client

media_folder: /public/media
public_folder: /media

collections:
  - name: blog-zh
    label: 中文博客
    label_singular: blog-zh
    folder: /src/blog/zh
    create: true
    delete: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: pubDate, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: Description, name: description, widget: text }
      - { label: Author, name: author, widget: string }
      - label: Image
        name: image
        widget: object
        fields:
          - { label: URL, name: url, widget: string }
          - { label: Alt Text, name: alt, widget: string }
      - { label: Tags, name: tags, widget: list, field: { label: Tag, name: tag, widget: string } }
      - { label: Body, name: body, widget: markdown }

  - name: blog-en
    label: blog
    label_singular: blog-en
    folder: /src/blog/en
    create: true
    delete: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: pubDate, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: Description, name: description, widget: text }
      - { label: Author, name: author, widget: string }
      - label: Image
        name: image
        widget: object
        fields:
          - { label: URL, name: url, widget: string }
          - { label: Alt Text, name: alt, widget: string }
      - { label: Tags, name: tags, widget: list, field: { label: Tag, name: tag, widget: string } }
      - { label: Body, name: body, widget: markdown }


# Media provider features
media_libraries:
  # default:
  #   config:
  #     max_file_size: 1024000 # default: Infinity
  #     slugify_filename: true # default: false
  #     transformations: # See the documentation for details

  cloudflare_r2:
    access_key_id: 852bd16c78142bd7dbf82ea2a9e7a2ee
    bucket: figures
    account_id: 6739ed328656ada25d8eb1c4c033da5b
    public_url: https://figures.de5.net
    prefix: images/ # Optional
    jurisdiction: default # Optional; 'default' | 'eu' | 'fedramp'

  cloudinary:
    config:
      cloud_name: dbxprwscm
      api_key: 329376394623687
    output_filename_only: false
    use_transformations: true